# ZERO TIER NETWORK
drones:
  mother_drone_1:
    connection_string: "tcp:10.242.134.79:5763"
    system_id: 1
    child_drones:
      - drone_2
      - drone_3
  drone_2:
    connection_string: "tcp:10.242.134.79:5773"
    system_id: 2
  drone_3:
    connection_string: "tcp:10.242.134.79:5783"
    system_id: 3

  mother_drone_2:
    connection_string: "tcp:10.242.134.79:5793"
    system_id: 4
    child_drones:
      - drone_4
      - drone_5
  drone_4:
    connection_string: "tcp:10.242.134.79:5803"
    system_id: 5
  drone_5:
    connection_string: "tcp:10.242.134.79:5813"
    system_id: 6

  mother_drone_3:
    connection_string: "tcp:10.242.134.79:5823"
    system_id: 7
    child_drones:
      - drone_6
      - drone_7
  drone_6:
    connection_string: "tcp:10.242.134.79:5833"
    system_id: 8
  drone_7:
    connection_string: "tcp:10.242.134.79:5843"
    system_id: 9
  
  mother_drone_4:
    connection_string: "tcp:10.242.134.79:5853"
    system_id: 10
    child_drones:
      - drone_8
      - drone_9
  drone_8:
    connection_string: "tcp:10.242.134.79:5863"
    system_id: 11
  drone_9:
    connection_string: "tcp:10.242.134.79:5873"
    system_id: 12

settings:
  separation_time: 5.0  # Minimum separation distance in meters

waypoints:
  mission_1:
    - latitude: -35.361297
      longitude: 149.161120
      altitude: 50.0
      command: 16  # MAV_CMD_NAV_WAYPOINT
    - latitude: -35.360780
      longitude: 149.167151
      altitude: 50.0
      command: 16
    - latitude: -35.365115
      longitude: 149.167647
      altitude: 50.0
      command: 16
    - latitude: -35.364419
      longitude: 149.161575
      altitude: 50.0
      command: 16
    - latitude: -35.3632621  # Home location
      longitude: 149.1652374
      altitude: 0.0
      command: 16
  mission_2:
    - latitude: -35.140018
      longitude: 150.728241
      altitude: 100.0
      command: 16  # MAV_CMD_NAV_WAYPOINT
    - latitude: -35.130000
      longitude: 150.740000
      altitude: 100.0
      command: 16  # Moving northeast
    - latitude: -35.120000
      longitude: 150.728241
      altitude: 100.0
      command: 16  # Moving north
    - latitude: -35.130000
      longitude: 150.715000
      altitude: 100.0
      command: 16  # Moving northwest
    - latitude: -35.140018
      longitude: 150.728241
      altitude: 100.0
      command: 16  # Returning to starting point
  mission_3:
    - latitude: -35.150000
      longitude: 150.728241
      altitude: 100.0
      command: 16  # MAV_CMD_NAV_WAYPOINT
    - latitude: -35.140000
      longitude: 150.740000
      altitude: 100.0
      command: 16  # Moving northeast
    - latitude: -35.130000
      longitude: 150.752000
      altitude: 100.0
      command: 16  # Moving east
    - latitude: -35.120000
      longitude: 150.740000
      altitude: 100.0
      command: 16  # Moving southeast
    - latitude: -35.110000
      longitude: 150.728241
      altitude: 100.0
      command: 16  # Moving south
    - latitude: -35.120000
      longitude: 150.715000
      altitude: 100.0
      command: 16  # Moving southwest
    - latitude: -35.130000
      longitude: 150.715000
      altitude: 100.0
      command: 16  # Moving west
    - latitude: -35.150000
      longitude: 150.728241
      altitude: 100.0
      command: 16  # Returning to starting point
  mission_4:
    - latitude: -35.140018
      longitude: 150.728241
      altitude: 100.0
      command: 16  # MAV_CMD_NAV_WAYPOINT
    - latitude: -35.145000
      longitude: 150.740000
      altitude: 100.0
      command: 16  # Moving northeast
    - latitude: -35.135000
      longitude: 150.750000
      altitude: 100.0
      command: 16  # Moving east
    - latitude: -35.125000
      longitude: 150.740000
      altitude: 100.0
      command: 16  # Moving southeast
    - latitude: -35.115000
      longitude: 150.730000
      altitude: 100.0
      command: 16  # Moving south
    - latitude: -35.125000
      longitude: 150.715000
      altitude: 100.0
      command: 16  # Moving southwest
    - latitude: -35.135000
      longitude: 150.715000
      altitude: 100.0
      command: 16  # Moving west
    - latitude: -35.140018
      longitude: 150.728241
      altitude: 100.0
      command: 16  # Returning to starting point

fence:
  coordinates:
    - [-35.363152, 149.164795]
    - [-35.361019, 149.161057]
    - [-35.360817, 149.168533]
    - [-35.365364, 149.168686]
    - [-35.365486, 149.160919]
    - [-35.363792, 149.160919]
    - [-35.363747, 149.163574]
    - [-35.362366, 149.163666]
    - [-35.362286, 149.161011]
    - [-35.361019, 149.161057]

rally:
  coordinates:
    - [-35.361235, 149.161052, 100.000000]
    - [-35.362089, 149.164452, 100.000000]
    - [-35.364099, 149.161712, 100.000000]
    - [-35.363649, 149.166642, 100.000000]
    - [-35.359978, 149.168170, 100.000000]